# Generated by Django 4.2 on 2026-01-07 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='clothing/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('black', 'Черный'), ('white', 'Белый'), ('pink', 'Розовый'), ('yellow', 'Желтый'), ('purple', 'Фиолетовый'), ('brown', 'Коричневый'), ('gray', 'Серый'), ('beige', 'Бежевый'), ('multicolor', 'Разноцветный')], max_length=20, verbose_name='Цвет')),
                ('category', models.CharField(choices=[('top', 'Верх'), ('bottom', 'Низ'), ('outer', 'Верхняя одежда'), ('dress', 'Костюм/Платье'), ('shoes', 'Обувь'), ('accessory', 'Аксессуары')], max_length=20, verbose_name='Категория')),
                ('season', models.CharField(max_length=50, verbose_name='Сезон')),
                ('occasion', models.CharField(choices=[('office', 'В офис'), ('home', 'Для дома'), ('walk', 'На прогулку'), ('party', 'На праздник'), ('any', 'Любой')], default='any', max_length=20, verbose_name='Тип мероприятия')),
                ('rating', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=3, verbose_name='Личная оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название образа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('occasion', models.CharField(choices=[('office', 'В офис'), ('home', 'Для дома'), ('walk', 'На прогулку'), ('party', 'На праздник'), ('any', 'Любой')], default='any', max_length=20, verbose_name='Тип мероприятия')),
                ('rating', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=3, verbose_name='Личная оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('items', models.ManyToManyField(to='wardrobe.clothingitem', verbose_name='Вещи в образе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образы',
                'ordering': ['-created_at'],
            },
        ),
    ]
