# Generated by Django 4.2.11 on 2026-01-11 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='times_shown',
            field=models.IntegerField(default=0, verbose_name='Показов'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='occasion',
            field=models.CharField(max_length=100, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(max_length=100, verbose_name='Тип мероприятия'),
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Оценка совместимости')),
                ('times_evaluated', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_item1', to='wardrobe.clothingitem')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_item2', to='wardrobe.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Совместимости',
                'unique_together': {('user', 'item1', 'item2')},
            },
        ),
    ]
